name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: 'Cache: .nuke/temp, ~/.nuget/packages'
      uses: actions/cache@v3
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('global.json', 'source/**/*.csproj') }}
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Set build script eXecutable
      run: chmod +x ./build.sh
    - name: 'Run: Nuke build'
      run: ./build.sh --target Pack --verbosity verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
